[package]
name = "rust_gp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = { version = "1.0.193", features = ["derive"] }
log = "0.4.20"
csv = "1.3.0"
